# Generated by Django 5.1.3 on 2024-12-30 15:03

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dentists",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField()),
                ("administrator", models.BooleanField()),
                ("disabled", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consults",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("category", models.TextField()),
                ("description", models.TextField()),
                ("amount", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("expected_visit_date", models.DateTimeField(blank=True, null=True)),
                ("index", models.SmallIntegerField(blank=True, null=True)),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smileapp.dentists",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultNotes",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "consult",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smileapp.consults",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smileapp.dentists",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.TextField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("smile_goals", models.TextField()),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("stage", models.TextField()),
                ("category", models.TextField(blank=True, null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smileapp.dentists",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sender_id", models.UUIDField()),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("patient", "Patient"), ("dentist", "Dentist")],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="smileapp.dentists",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="smileapp.patients",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consults",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="smileapp.patients"
            ),
        ),
        migrations.CreateModel(
            name="RAFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("title", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("src", models.URLField()),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="smileapp.messages",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("color", models.TextField()),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smileapp.dentists",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("text", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField()),
                ("done_date", models.DateTimeField(blank=True, null=True)),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smileapp.dentists",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smileapp.patients",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="messages",
            constraint=models.CheckConstraint(
                condition=models.Q(("text__isnull", False)), name="text_required"
            ),
        ),
    ]
