# Generated by Django 5.1.3 on 2024-12-18 11:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dentists',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('administrator', models.BooleanField()),
                ('disabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('stage', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('expected_visit_date', models.DateTimeField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smileapp.dentists')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileapp.consults')),
                ('dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smileapp.dentists')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('smile_goals', models.TextField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('stage', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileapp.dentists')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileapp.dentists')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileapp.patients')),
            ],
        ),
        migrations.AddField(
            model_name='consults',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileapp.patients'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('done_date', models.DateTimeField(blank=True, null=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileapp.dentists')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileapp.patients')),
            ],
        ),
    ]
