# Generated by Django 5.1.3 on 2025-01-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smileapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rafile",
            name="id",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="rafile",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="smileapp.messages",
            ),
        ),
        migrations.AlterField(
            model_name="rafile",
            name="path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rafile",
            name="src",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="rafile",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
